[build]
  command = "npm run build:static"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_BASE_PATH = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 